### PR TITLE
upgrade request version

### PR DESCRIPTION
**Pull request by rcarroll380**
New vulnerability with request: https://nodesecurity.io/advisories/130

### CODE REVIEW

**Comment by michaelckelly** [comment]
Thanks for the PR, @rcarroll380. Change LGTM, though our CI tests did not run. Investigating.

**Comment by michaelckelly** [comment]
@rcarroll380  - Can you please force push this branch? Attempting to get CI running. If that fails, I'll handle it manually.

**Comment by rcarroll380** [comment]
@michaelckelly I am getting everything up to date when I force push my branch.

**Comment by michaelckelly** [comment]
@rcarroll380  Could you try an amend + force push, i.e:

```
git commit --amend --no-edit && git push ...
```

**Comment by michaelckelly** [comment]
Thanks @rcarroll380, change LGTML

**Comment by michaelckelly** [comment]
Published as [1.0.11][1]

[1]: https://www.npmjs.com/package/plaid

**Comment by rcarroll380** [comment]
Thank you!

**Pull request merged**
