### PR TITLE
Add options param to getInstitutions TS definition

### LINKED ISSUE #226: getInstitutions typescript definition doesn't have options param
`getInstitutions` method within PlaidClient.js already accepts the `options` param, but the typescript definition doesn't

```
Client.prototype.getInstitutions =
  function(count, offset, options, cb) {
    return this._authenticatedRequest({
      path: '/institutions/get',
      body: {
        count: count,
        offset: offset
      },
    }, options, cb);
  };
```
Following error is shown when using typescript:

```Argument of type '{ include_optional_metadata: boolean; }' is not assignable to parameter of type 'Callback<GetInstitutionsResponse<Institution>>'.```

### PR DESCRIPTION
**Pull request by jabas06**
Add options param to getInstitutions TS definition

Fixes #226

### CODE REVIEW

**Comment by jabas06** [comment]
Hi, @pbernasconi is there any change to merge open PRs regarding TypeScript definitions?

Glad to help.

**Comment by skylarmb** [comment]
Hi @jabas06! If you could rebase / solve conflicts here I'm happy to approve/merge this for you

**Comment by jabas06** [comment]
Hi @skylarmb, I have accidentally closed the PR. Changes were already rebased, could you reopen it, please?

**Comment by skylarmb** [comment]
image

I am also unable to re-open the PR, not sure why. Open a new one and ping me! Thanks!

**Comment by skylarmb** [comment]
sorry, guess its just easier for me to open it. Done: https://github.com/plaid/plaid-node/pull/250

**Pull request closed without merging**
