### PR TITLE
update request dependency

### PR DESCRIPTION
**Pull request by esetnik**
make `request` dependency version range more flexible. See #143 for more info.

### CODE REVIEW

**Comment by jpokrzyk** [comment]
@ntindall @michaelckelly 

Can we get this one merged in? That warning is super annoying. Doesn't seems like there would be any controversy here.

**Comment by jpokrzyk** [comment]
Sweet. Thanks.

**Comment by esetnik** [comment]
Can we release plaid 2.2.1 with this change?

**Comment by ntindall** [comment]
Sorry for the delay @jpokrzyk @esetnik! We just published this as `2.3.0`.

Thanks for doing this.

**Pull request merged**
