### PR TITLE
OpenAPI generated code at 2023-08-15T23:29:35Z

### PR DESCRIPTION
**Pull request by aarohmankad**

### CODE REVIEW

**Review by jking-plaid — APPROVED** [review]

**Comment by amazingandyyy** [comment]
how to does this doc is generated by OpenAI?

**Comment by aarohmankad** [comment]
> how did this doc be generated by OpenAI?

Hey @amazingandyyy! We use an OpenAPI spec to generate our client libraries to maintain parity between the libraries of each language. I think you might have read that as OpenAI instead of OpenAPI.

**Comment by amazingandyyy** [comment]
vert very cool! what's the script to run the openapi spec? didn't see it in package.json.scripts

**Comment by aarohmankad** [comment]
@amazingandyyy: It's specified in our `openapi` repo! https://github.com/plaid/plaid-openapi

**Pull request merged**
